addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "$sbt_docker_version$")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "$sbt_native_packager_version$")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "$sbt_release_version$")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "$sbt_scoverage_version$")
addSbtPlugin("io.spray" % "sbt-revolver" % "$sbt_revolver_version$")